### ISSUE TITLE
DB_SERVER mismatched with parameter

### ISSUE THREAD

**Issue by usernameforgary** [databacker/mysql-backup#122]
Hi,

I tried to backup mysql db. With commands showing attached file.
Problem is, seems the actual DB_SERVER used while try to backup db is not the one which i typed in the -e DB_SERVER="172.17.0.2".
<img width="893" alt="1" src="https://user-images.githubusercontent.com/11784843/68700290-9b436880-05bf-11ea-8f90-77508d1844fc.png">

**Comment by deitch** [comment]
Hi @usernameforgary . 

Two requests:

* can you please cut and paste rather than screenshot (or in addition)?
* can you run it with debug to see what it is doing and paste the results? If too big, dump it in a gist. `-e DB_DUMP_DEBUG=true`. 

Please be sure to review the logs to make sure you don't share any secrets, of course.

**Comment by usernameforgary** [comment]
Hi @deitch .

It's my fault.
First, I run the docker with wrong mysql credential.
Second, I have no write permission for the mounted volume on the docker container. 

Sorry for that, and close this issue.
