### ISSUE TITLE
Request: Build arm64 target

### ISSUE THREAD

**Issue by Fossil01** [databacker/mysql-backup#221]
Trying to run this on my M1 Macbook which needs an arm64 image.

**Comment by st3iny** [comment]
The release workflow is already building an arm64 image. However, there was no release since this change and thus there is no tagged image compatible arm64 yet.

https://github.com/databacker/mysql-backup/blob/a071f62c6f6d28f580bf41edb81456071e020b9d/.github/workflows/release.yaml#L39

In the meantime, you could pull a development version of the image which is compatible with arm64: https://hub.docker.com/layers/databack/mysql-backup/a071f62c6f6d28f580bf41edb81456071e020b9d/images/sha256-84ddc7fb1e116ccf704a458254f810c1ab88e11d43e4aaaec30147be39efd2ea?context=explore

I also setup an automation that builds an arm64 image of the v0.11.0 tag at: https://github.com/st3iny/mysql-backup-arm64
The image is pushed to: ghcr.io/st3iny/mysql-backup-arm64:v0.11.0

**Comment by deitch** [comment]
Well, that should be easy enough to fix. Just pushed out v0.12.0. Should be through CI in a little while. Seek it out here https://hub.docker.com/r/databack/mysql-backup/tags

**Comment by st3iny** [comment]
Well that was quick. Thank you very much!
